FROM mcr.microsoft.com/dotnet/aspnet:5.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build
WORKDIR /src
COPY ["PaymentGateway.Api/PaymentGateway.Api.csproj", "PaymentGateway.Api/"]
COPY ["PaymentGateway.Services.Contracts/PaymentGateway.Data.Contracts.csproj", "PaymentGateway.Services.Contracts/"]
COPY ["PaymentGateway.Models.Contracts/PaymentGateway.Models.Contracts.csproj", "PaymentGateway.Models.Contracts/"]
COPY ["AcquiringBank.Contracts/PaymentGateway.AcquiringBank.Contracts.csproj", "AcquiringBank.Contracts/"]
COPY ["AcquiringBank.InMemory/AcquiringBank.InMemory.csproj", "AcquiringBank.InMemory/"]
COPY ["PaymentGateway.Services/PaymentGateway.Data.InMemory.csproj", "PaymentGateway.Services/"]
COPY ["PaymentGateway.Models/PaymentGateway.Models.csproj", "PaymentGateway.Models/"]
COPY ["PaymentGateway.Utils/PaymentGateway.Utils.csproj", "PaymentGateway.Utils/"]
RUN dotnet restore "PaymentGateway.Api/PaymentGateway.Api.csproj"
COPY . .
WORKDIR "/src/PaymentGateway.Api"
RUN dotnet build "PaymentGateway.Api.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "PaymentGateway.Api.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "PaymentGateway.Api.dll"]