name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  # github.repository as <account>/<repo>
  TAG_NAME: checkout-paymentgatewayapi:$(date +%s)
  
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build .. --file dockerfile --tag ${{ env.TAG_NAME }}
      working-directory: src/PaymentGateway.Api
    - name: publish the Docker image
      run: docker push petefield/checkout:${{ env.TAG_NAME }}
      working-directory: src/PaymentGateway.Api 
