name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build the Docker image
      run: docker build .. --file dockerfile --tag petefield/checkout:tagname
      working-directory: src/PaymentGateway.Api
    - name: publish the Docker image
      run: docker push petefield/checkout:latest
      working-directory: src/PaymentGateway.Api 
