name: Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set Tag name
      run: echo "tag=${{ github.run_number }}" >> $GITHUB_ENV
    - name: Build the Docker image
      run: docker build .. --file dockerfile --tag petefield/checkout
      working-directory: src/PaymentGateway.Api
    - name: login
      run:  docker login -u  ${{ secrets.DOCKERHUBUSERID }} -p  ${{ secrets.DOCKERHUBPASSWORD }}
    - name: publish the Docker image
      run: docker push petefield/checkout
      working-directory: src/PaymentGateway.Api 
    - name: logout
      run:  docker logout
