name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
env:
  tag: ${GITHUB_RUN_ID}-${GITHUB_RUN_NUMBER}

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build the Docker image
      run: docker build .. --file dockerfile --tag petefield/checkout:${{ env.tag }}
      working-directory: src/PaymentGateway.Api
    - name: publish the Docker image
      run: docker push petefield/checkout:${{ env.tag }}
      working-directory: src/PaymentGateway.Api 
